[package]
name = "java-parser"
version = "0.1.0"
authors = ["Thomas Cheng <thomascheng1998@googlemail.com>"]

[dependencies]
regex = "0.2"

[profile.release]
debug = true

[features]

# Set this feature whilst benching, enables unstable nightly features for
# benching.
bench = []
